Fix exception in `SMWExportController` for `&stats` option
Using `Special:ExportRDF&stats=true` causes a "Catchable
fatal error: Argument 1 passed to SMWExpData::__construct()
must be an instance of SMWExpResource, instance of
SMWExpLiteral given"