Disjuntive query for categories causes syntax error on sqlite
Query: INSERT  INTO sunittest_t1 (id) VALUES ('52'),('54')
Function: SMW\SQLStore\QueryEngine\QuerySegmentListResolver::fillHierarchyCacheForTableId
Error: 1 near ",": syntax error